# Generated by Django 4.0.4 on 2022-06-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Homeworks',
            new_name='Libros',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Recetas',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Viajes',
        ),
    ]
