# Generated by Django 4.0.4 on 2022-06-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0002_peliculas_rename_homeworks_libros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='email',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='profession',
        ),
    ]
