# Generated by Django 4.0.4 on 2022-06-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0003_remove_recetas_email_remove_viajes_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='last_name',
        ),
    ]
