# Generated by Django 4.0.4 on 2022-06-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0004_remove_libros_due_date_remove_libros_is_delivered_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recetas',
            new_name='Gastronomia',
        ),
    ]
