# Generated by Django 4.0.4 on 2022-06-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0005_rename_recetas_gastronomia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='last_name',
        ),
    ]
