# Generated by Django 4.0.4 on 2022-06-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0007_gastronomia_plot_libros_plot_peliculas_plot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
