# Generated by Django 4.0.4 on 2022-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0008_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastronomia',
            name='plot',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='libros',
            name='plot',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='plot',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='plot',
            field=models.CharField(max_length=150),
        ),
    ]
